name: Build
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    name: Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: gradle
      - name: Setup gradle build cache
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true # namespace handles this
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: "" # namespace handles thi
      - run: ./gradlew --init-script=/tmp/init.gradle build --stacktrace --console=colored
