name: Deploy
on:
  push:
    tags: ['v*']

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build publish --stacktrace --console=colored
        env:
          ORG_GRADLE_PROJECT_papermcUsername: ${{ secrets.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_papermcPassword: ${{ secrets.DEPLOY_PASS }}
      - name: Get tag name
        id: get_tag
        shell: bash
        run: |
          tag_name="$(echo $GITHUB_REF | cut -d / -f 3)"
          echo "tag=$tag_name" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: 'Release ${{ steps.get_tag.outputs.tag }}'
          prerelease: false
          draft: false
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
