name: Deploy Snapshot
on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
      - '.gitignore'
      - '.gitattributes'

jobs:
  deploy:
    name: Deploy Snapshot
    runs-on: 'ubuntu-latest'
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: gradle
      - name: Setup gradle build cache
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true # namespace handles this
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: "" # namespace handles thi
      - name: Get project version
        id: get_version
        shell: bash
        run: |
          project_version=$(./gradlew -q --console=plain printVersion)
          echo "version=$project_version" >> $GITHUB_OUTPUT
      - name: Deploy snapshot version
        if: endsWith(steps.get_version.outputs.version, '-SNAPSHOT')
        run: ./gradlew --init-script=/tmp/init.gradle build publish --stacktrace --console=colored
        env:
          ORG_GRADLE_PROJECT_papermcUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
          ORG_GRADLE_PROJECT_papermcPassword: ${{ secrets.ARTIFACTORY_PASSWORD }}
